### ISSUE TITLE
LIME not processing model response feature names

### ISSUE THREAD

**Issue by ruivieira** [trustyai-python/trustyai-explainability#512]
When using TrustyAI service with the loan ONNX model, requesting an explanation fails with

```
2024-03-06 22:59:14,339 INFO  [org.kie.tru.ser.dat.par.CSVParser] (executor-thread-2) Creating dataframe from CSV data
2024-03-06 22:59:14,350 ERROR [org.kie.tru.exp.loc.lim.HighScoreNumericFeatureZonesProvider] (executor-thread-2) Could not sort predictions by score io.grpc.StatusRuntimeException: INVALID_ARGUMENT: inference.GRPCInferenc
eService/ModelInfer: INVALID_ARGUMENT: Missing input with specific name - Required input: customer_data_input
2024-03-06 22:59:14,351 INFO  [org.kie.tru.ser.end.con.ConsumerEndpoint] (executor-thread-1) Received partial input payload from model='demo-loan-nn-onnx-beta', id=58-3
2024-03-06 22:59:14,353 INFO  [org.kie.tru.ser.end.con.ConsumerEndpoint] (executor-thread-1) Received partial output payload from model='demo-loan-nn-onnx-beta', id=58-3
2024-03-06 22:59:14,353 ERROR [org.kie.tru.ser.end.con.ConsumerEndpoint] (executor-thread-1) Invalid schema for payload response id=58-3, Error parsing output payload: Data outputs count not supported: 0
2024-03-06 22:59:14,359 ERROR [org.kie.tru.ser.end.exp.loc.LimeEndpoint] (executor-thread-2) SimplePrediction{input=PredictionInput{features=[Feature{name='customer_data_input-0', type=number, value=0.0}, Feature{name='cu
stomer_data_input-1', type=number, value=270000.0}, Feature{name='customer_data_input-2', type=number, value=1.0}, Feature{name='customer_data_input-3', type=number, value=0.0}, Feature{name='customer_data_input-4', type=
number, value=1.0}, Feature{name='customer_data_input-5', type=number, value=1.0}, Feature{name='customer_data_input-6', type=number, value=0.0}, Feature{name='customer_data_input-7', type=number, value=1.0}, Feature{name
='customer_data_input-8', type=number, value=0.0}, Feature{name='customer_data_input-9', type=number, value=16582.0}, Feature{name='customer_data_input-10', type=number, value=1194.0}]},output=PredictionOutput{outputs=[Ou
tput{value=1, type=number, score=0.0, name='predict'}]}}: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: inference.GRPCInferenceService/ModelInfer: INVALID_ARGUMENT: Missing inp
ut with specific name - Required input: customer_data_input
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
    at org.kie.trustyai.service.endpoints.explainers.local.LimeEndpoint.generateExplanation(LimeEndpoint.java:67)
    at org.kie.trustyai.service.endpoints.explainers.local.LocalExplainerEndpoint.processRequest(LocalExplainerEndpoint.java:49)
    at org.kie.trustyai.service.endpoints.explainers.local.LimeEndpoint.explain(LimeEndpoint.java:59)
    at org.kie.trustyai.service.endpoints.explainers.local.LimeEndpoint$quarkusrestinvoker$explain_b291255528c2fa467fb1c11442fae69e11d2bf1b.invoke(Unknown Source)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: inference.GRPCInferenceService/ModelInfer: INVALID_ARGUMENT: Missing input with specific name - Required input: customer_data_input
    at io.grpc.Status.asRuntimeException(Status.java:539)
    at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:548)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    ... 1 more
```

**Comment by ruivieira** [comment]
Duplicate of https://github.com/trustyai-explainability/trustyai-explainability/issues/522
